##########################
## PR to Main  - GitOps ##
##########################

# integrate with 'release-me' git ops event

# Triggers on PR closed with merged code and when PR title starts with '[GITOPS]' string

on:
  pull_request:
    types: [closed]
    branches:  # ALLOWED Base Branches
      - release

jobs:
  open_pr_to_main:
    if: github.event.pull_request.merged == true && (
      startsWith(github.event.pull_request.title, '[GITOPS]')
      )
    uses: boromir674/automated-workflows/.github/workflows/go-pr-to-main.yml@dev-branch
    with:
      RELEASE: 'release'
      MAIN_BR: ${{ vars.GIT_MAIN_BRANCH || 'main' }}
    secrets:
      GH_TOKEN: '${{ secrets.PR_RW_AND_ACTIONS_RW }}'
