###############################################
## PR to Release with Auto Merge - GitOps ##
###############################################

# export tt='board-request'; git tag -d "$tt"; git push --delete origin "$tt"; git tag "$tt" && git push origin "$tt"

on:
  push:
    tags:
      - release-me  # Request to be included in next Release and create a Release

jobs:

  pr_to_release:
    uses: boromir674/automated-workflows/.github/workflows/go-pr-to-release.yml@test
    with:
      # pass tag to PR from <user_branch>  -->  <github.ref>-<user_branch>
      release_branch: ${{ vars.GITOPS_RELEASE_BRANCH || "release" }}
    secrets:
      # since job does not do auto merge pat needs only read/write to PRs
      github_pat: ${{ secrets.PR_RW_AND_ACTIONS_RW }}
